name: Deploy to AWS
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin 724560470446.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build, Tag & Push Docker Image
        run: |
          docker build -t devops-app .
          docker tag devops-app:latest 724560470446.dkr.ecr.ap-south-1.amazonaws.com/1st:latest
          docker push 724560470446.dkr.ecr.ap-south-1.amazonaws.com/1st:latest
